#define S_LIGHTING_VISUAL_PLANE 115
#define S_LIGHTING_VISUAL_RENDER_TARGET "S_LIGHT_VISUAL_PLANE"

#define WEATHER_OVERLAY_PLANE -3
#define WEATHER_RENDER_TARGET "*WEATHER_OVERLAY_PLANE"

#define WEATHER_EFFECT_PLANE -2
