#define COMSIG_XENO_PRE_SPIT "xeno_spit_before_generation"

#define XENO_STRUCTURE_SUNKEN  "sunken colony"

#define XENO_SHIELD_SOURCE_SPITTER_SUPPRESSOR 11

#define XENO_COMM_ACQUISITION_TIME (45 MINUTES)

#define XENO_SHIELD_SACRIFICE 12

#define LESSER_BUILD_COLOR "#cbc8fc"

#define LESSER_SHIELD_OVERLAY 9
