/obj/item/storage/box/m56c_system/Initialize()
	. = ..()
	new /obj/item/clothing/glasses/night/m56_goggles(src)
	new /obj/item/weapon/gun/smartgun/m56c(src)
	new /obj/item/storage/large_holster/machete/smartgunner(src)
	new /obj/item/smartgun_battery(src)
	new /obj/item/clothing/suit/storage/marine/smartgunner(src)
	new /obj/item/storage/belt/marine/smartgunner/m56c(src)
	update_icon()
